### ISSUE TITLE
一个Api接口映射多个URI路径会报异常

### ISSUE THREAD

**Issue by lins3000** [jetplugins/apidocx#62]
例如：
@GetMapping({"selectByTenantId","selectByCondition"})
生成接口文档时会报异常：
java.lang.ClassCastException: class com.google.gson.internal.LinkedTreeMap cannot be cast to class io.apidocx.model.Api (com.google.gson.internal.LinkedTreeMap and io.apidocx.model.Api are in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @3f3ae47)
	at io.apidocx.parse.ApiParser.lambda$doParseMethod$1(ApiParser.java:132)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at io.apidocx.parse.ApiParser.doParseMethod(ApiParser.java:141)
	at io.apidocx.parse.ApiParser.parse(ApiParser.java:84)

**Comment by lkqm** [comment]
好的谢谢大概知道问题了

**Comment by lkqm** [comment]
已经修复，最近会发布版本
